// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraphQLWebService.Models
{
    public partial class School
    {
        public School()
        {
            Students = new HashSet<Student>();
            Workshops = new HashSet<Workshop>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int TownId { get; set; }

        public virtual Town Town { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Workshop> Workshops { get; set; }
    }
}