// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraphQLWebService.Models
{
    public partial class Town
    {
        public Town()
        {
            Schools = new HashSet<School>();
        }

        public int Id { get; set; }
        public int Postcode { get; set; }
        public string Name { get; set; }

        public virtual ICollection<School> Schools { get; set; }
    }
}